---
ID: "d158a9ce-4945-40c6-b54f-7bdd0b720199"
Parent: "a1854dfd-e74f-42ab-a85e-e0f566c5679c"
Template: "a1854dfd-e74f-42ab-a85e-e0f566c5679c"
Path: /sitecore/templates/Project/Sugcon2024/List Components/Icon Link List/Icon Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{87812D49-5E8C-4520-BAB1-78B0E47313C4}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240215T161648Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "54387a94-d0ad-479a-9cc8-d2eca3e2649d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240215T162343Z
