---
ID: "2d7d8c06-ed5a-5ade-8105-5c88414b8749"
Parent: "bbb4c1c3-26e5-5dc0-b112-ef72ab98fcbe"
Template: "bbb4c1c3-26e5-5dc0-b112-ef72ab98fcbe"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-Section Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144942Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "162a6720-0a59-4e31-b627-31792b744ad3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144942Z
