---
ID: "84ffebf2-7bde-5ac8-802d-8f3c86817516"
Parent: "1f454fb4-a841-5c44-84fd-a9a346bf83c0"
Template: "1f454fb4-a841-5c44-84fd-a9a346bf83c0"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-CustomRouteType Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144935Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "26d8fbbb-519a-42f7-8447-ca187327dd95"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144935Z
