---
ID: "963425f8-1e12-5a2f-8dc8-4d46202a8d7a"
Parent: "7981cccc-03ba-511d-8eb7-5bb4e24d3b9e"
Template: "7981cccc-03ba-511d-8eb7-5bb4e24d3b9e"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-FieldUsage-Date Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "12d26813-7b3f-47f2-ae48-5aaae8029f5c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144922Z
