---
ID: "9a2113c2-298e-4431-ba8d-2355210fdeef"
Parent: "94de9ac3-a9f7-40ab-ae90-acda364b9c40"
Template: "a054184c-3b20-4c2b-ab04-c8a03acd5522"
Path: "/sitecore/content/MvpSite/Home/Application-Closed"
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{18395B95-5177-474A-99E4-D76A9EDE44D0}">
          <p:d />
        </r>
        <r
          uid="{C663F483-8FCC-4F90-904E-9A4902F18AF3}"
          p:after="r[@uid='{D842E8EB-450E-4348-A54A-E60CF16E9E52}']"
          s:ds="{FAFF75EC-FCCE-4FF8-B0CF-7DC54FA40244}"
          s:id="{248BDE7D-D010-4D02-95E8-2578A03A2D2D}"
          s:par=""
          s:ph="main" />
        <r
          uid="{64CD74AD-6939-48FB-ABB9-33F2403ED031}"
          p:after="r[@uid='{C663F483-8FCC-4F90-904E-9A4902F18AF3}']" />
        <r
          uid="{79A3FA45-98FD-4752-B819-43984684A450}"
          p:after="*[1=2]"
          s:id="{00147A0F-476B-4C99-8A10-E6B4FCFCECE0}"
          s:ph="header-signin" />
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{9AC6DDA3-8785-4C63-A2AB-457D8CC56D19}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{39294090-558E-4FD8-AAA8-F4B6DAC04125}"
              p:before="*"
              s:ds=""
              s:id="{AA449EA4-0695-4D4C-9CD3-E582738A355E}"
              s:par=""
              s:ph="/main/page-overview-panel-{3920C133-2B8C-49B6-B473-448DC3EE5DCC}-0"
              s:ccb="Clear on publish" />
            <r
              uid="{C663F483-8FCC-4F90-904E-9A4902F18AF3}"
              s:ccb="Clear on publish"
              s:ds="{277FD545-7E30-495C-AFEF-A20159D06232}" />
            <r
              uid="{3920C133-2B8C-49B6-B473-448DC3EE5DCC}"
              p:after="r[@uid='{C663F483-8FCC-4F90-904E-9A4902F18AF3}']"
              s:id="{DF26CA0D-A60B-4349-8908-E7A62F7E7272}"
              s:ph="main" />
            <r
              uid="{64CD74AD-6939-48FB-ABB9-33F2403ED031}"
              p:after="*[1=2]" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211130T202032Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7265b607-0c89-4b1a-8fa2-752798b47840"
    - ID: "b1ece12f-b2c9-44e6-92a3-c5dfd6514b59"
      Hint: MenuTitle
      Value: Application
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rob
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220406T045653Z
    - ID: "efc0a3c7-6993-47d2-ba85-10b44961916e"
      Hint: IncludeInMenu
      Value: 
