---
ID: "ce3a2bdb-08fa-4fe2-8a25-9a50da861087"
Parent: "b9e0c2e9-07f3-4ebb-9e10-cfea08422e1f"
Template: "b9e0c2e9-07f3-4ebb-9e10-cfea08422e1f"
Path: /sitecore/templates/Project/Sugcon2024/List Components/Rendering Parameters/People Grid/__Standard Values
