---
ID: "68196976-0e13-4ab1-9085-8ffd529e45e8"
Parent: "c34e4ad8-acd9-4a7f-904e-c52533153603"
Template: "2f1ea555-8e46-42b5-825d-b6ad690e281a"
Path: /sitecore/content/MvpSite/Shared Content/Selections/Admin/Applications Overview
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220905T133130Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b81983d0-6f33-4f7e-93eb-32cdff2668aa"
    - ID: "a8e81d10-91db-4d09-a5cc-160d049c0c2e"
      Hint: CountryTableHeader
      Value: Country/Territory
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tamas.varga@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221027T134847Z
