---
ID: "2d3b8540-99c6-48b8-8f20-5be72bdcbc6b"
Parent: "3b4fe61f-6c96-4d2e-b6e0-856463bffef5"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/Sugcon/SuconShared/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{8EEF67D6-1E5B-40C0-AA0C-1F0B5ADC7797}|{9B0E6AF1-B383-4305-B11F-A9B5F13564BA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220523T080408Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0a21fa32-ad18-41ad-8eb4-eb6436103487"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220523T080500Z
