---
ID: "11d51477-3f29-4d05-bf5d-0a0757ab6720"
Parent: "908ce315-5c67-40f3-920e-9aca6c348318"
Template: "908ce315-5c67-40f3-920e-9aca6c348318"
Path: /sitecore/templates/Project/Sugcon2024/List Components/People Grid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240314T055643Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "68fc3baf-c3d9-4b1f-a360-3f285e756807"
      Hint: Headline
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad2a16e0-cba6-4e87-899d-f66ae698e67b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240314T055648Z
