---
ID: "d14f66b4-e862-4558-b6bc-4225a5e0f0e3"
Parent: "51e6498e-70a9-4ca5-9ccd-f0633e50eb62"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Project/Sugcon2024/NA/Images/Sponsors/Netlify
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/D14F66B4E8624558B6BC4225A5E0F0E3.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "b048e6c5-c2c1-4ca5-9976-9ee171c7c1b7"
  Value: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTGF5ZXJfMiIgZGF0YS1uYW1lPSJMYXllciAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNTEyIDIwOC4xMyI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgY2xpcC1wYXRoOiB1cmwoI2NsaXBwYXRoKTsKICAgICAgfQoKICAgICAgLmNscy0yIHsKICAgICAgICBmaWxsOiBub25lOwogICAgICB9CgogICAgICAuY2xzLTIsIC5jbHMtMywgLmNscy00IHsKICAgICAgICBzdHJva2Utd2lkdGg6IDBweDsKICAgICAgfQoKICAgICAgLmNscy0zIHsKICAgICAgICBmaWxsOiAjMDViZGJhOwogICAgICB9CgogICAgICAuY2xzLTQgewogICAgICAgIGZpbGw6ICMwMTQ4NDc7CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgICA8Y2xpcFBhdGggaWQ9ImNsaXBwYXRoIj4KICAgICAgPHJlY3QgY2xhc3M9ImNscy0yIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjIwOC4xMyIvPgogICAgPC9jbGlwUGF0aD4KICA8L2RlZnM+CiAgPGcgaWQ9IkxheWVyXzEtMiIgZGF0YS1uYW1lPSJMYXllciAxIj4KICAgIDxnIGNsYXNzPSJjbHMtMSI+CiAgICAgIDxnPgogICAgICAgIDxwYXRoIGNsYXNzPSJjbHMtMyIgZD0ibTExNy40NCwyMDcuMDR2LTUyLjQzbDEuMDktMS4wOWgxMC45MmwxLjA5LDEuMDl2NTIuNDNsLTEuMDksMS4wOWgtMTAuOTJsLTEuMDktMS4wOVoiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Im0xMTcuNDQsNTMuNTJWMS4wOWwxLjA5LTEuMDloMTAuOTJsMS4wOSwxLjA5djUyLjQzbC0xLjA5LDEuMDloLTEwLjkybC0xLjA5LTEuMDlaIi8+CiAgICAgICAgPHBhdGggY2xhc3M9ImNscy0zIiBkPSJtNjkuOTUsMTY5LjI0aC0xLjU0bC03LjcyLTcuNzN2LTEuNTRsMTguMDMtMTguMDNoOC4xOHMxLjEsMS4wOSwxLjEsMS4wOXY4LjE4bC0xOC4wNCwxOC4wM1oiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Im02OS45NSwzOC44OWgtMS41NGwtNy43Miw3LjczdjEuNTRsMTguMDMsMTguMDNoOC4xOHMxLjEtMS4wOSwxLjEtMS4wOXYtOC4xOGwtMTguMDQtMTguMDNaIi8+CiAgICAgICAgPHBhdGggY2xhc3M9ImNscy0zIiBkPSJtMS4wOSw5Ny41MWg3NC4yOGwxLjA5LDEuMDl2MTAuOTJsLTEuMDksMS4wOUgxLjA5bC0xLjA5LTEuMDl2LTEwLjkybDEuMDktMS4wOVoiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Im00NDEsOTcuNTFoNjkuOTFsMS4wOSwxLjA5djEwLjkybC0xLjA5LDEuMDloLTc0LjI4bC0xLjA5LTEuMDksNC4zNy0xMC45MiwxLjA5LTEuMDlaIi8+CiAgICAgICAgPHBhdGggY2xhc3M9ImNscy00IiBkPSJtMjEyLjA2LDEwOC43M2wtMS4wOSwxLjA5aC0zMy44OGwtMS4wOSwxLjA5YzAsMi4xOSwyLjE5LDguNzQsMTAuOTMsOC43NCwzLjI4LDAsNi41Ni0xLjA5LDcuNjUtMy4yOGwxLjA5LTEuMDloMTMuMTJsMS4wOSwxLjA5Yy0xLjA5LDYuNTYtNi41NiwxNi40LTIyLjk1LDE2LjQtMTguNTgsMC0yNy4zMy0xMy4xMi0yNy4zMy0yOC40MnM4Ljc0LTI4LjQyLDI2LjIzLTI4LjQyLDI2LjIzLDEzLjEyLDI2LjIzLDI4LjQydjQuMzdoMFptLTE2LjQtMTAuOTNjMC0xLjA5LTEuMDktOC43NC05Ljg0LTguNzRzLTkuODQsNy42NS05Ljg0LDguNzRsMS4wOSwxLjA5aDE3LjQ5bDEuMDktMS4wOVoiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Im0yNDIuNjYsMTE1LjI4YzAsMi4xOSwxLjA5LDMuMjgsMy4yOCwzLjI4aDkuODRsMS4wOSwxLjA5djEwLjkzbC0xLjA5LDEuMDloLTkuODRjLTkuODQsMC0xOC41OC00LjM3LTE4LjU4LTE2LjR2LTI0LjA1bC0xLjA5LTEuMDloLTcuNjVsLTEuMDktMS4wOXYtMTAuOTNsMS4wOS0xLjA5aDcuNjVsMS4wOS0xLjA5di05Ljg0bDEuMDktMS4wOWgxMy4xMmwxLjA5LDEuMDl2OS44NGwxLjA5LDEuMDloMTIuMDJsMS4wOSwxLjA5djEwLjkzbC0xLjA5LDEuMDloLTEyLjAybC0xLjA5LDEuMDl2MjQuMDVoMFoiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Im0yODMuMSwxMzEuNjhoLTEzLjEybC0xLjA5LTEuMDlWNTYuMjZsMS4wOS0xLjA5aDEzLjEybDEuMDksMS4wOXY3NC4zMmwtMS4wOSwxLjA5WiIvPgogICAgICAgIDxwYXRoIGNsYXNzPSJjbHMtNCIgZD0ibTMxMi42MSw2OC4yOWgtMTMuMTJsLTEuMDktMS4wOXYtMTAuOTNsMS4wOS0xLjA5aDEzLjEybDEuMDksMS4wOXYxMC45M2wtMS4wOSwxLjA5Wm0wLDYzLjM5aC0xMy4xMmwtMS4wOS0xLjA5di01Mi40NmwxLjA5LTEuMDloMTMuMTJsMS4wOSwxLjA5djUyLjQ2bC0xLjA5LDEuMDlaIi8+CiAgICAgICAgPHBhdGggY2xhc3M9ImNscy00IiBkPSJtMzYzLjk4LDU2LjI2djEwLjkzbC0xLjA5LDEuMDloLTkuODRjLTIuMTksMC0zLjI4LDEuMDktMy4yOCwzLjI4djQuMzdsMS4wOSwxLjA5aDEwLjkzbDEuMDksMS4wOXYxMC45M2wtMS4wOSwxLjA5aC0xMC45M2wtMS4wOSwxLjA5djM5LjM1bC0xLjA5LDEuMDloLTEzLjEybC0xLjA5LTEuMDl2LTM5LjM1bC0xLjA5LTEuMDloLTcuNjVsLTEuMDktMS4wOXYtMTAuOTNsMS4wOS0xLjA5aDcuNjVsMS4wOS0xLjA5di00LjM3YzAtMTIuMDIsOC43NC0xNi40LDE4LjU4LTE2LjRoOS44NGwxLjA5LDEuMDloMFoiLz4KICAgICAgICA8cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Im00MDQuNDIsMTMyLjc3Yy00LjM3LDEwLjkzLTguNzQsMTcuNDktMjQuMDUsMTcuNDloLTUuNDdsLTEuMDktMS4wOXYtMTAuOTNsMS4wOS0xLjA5aDUuNDdjNS40NiwwLDYuNTYtMS4wOSw3LjY1LTQuMzd2LTEuMDlsLTE3LjQ5LTQyLjYzdi0xMC45M2wxLjA5LTEuMDloOS44NGwxLjA5LDEuMDksMTMuMTIsMzcuMTZoMS4wOWwxMy4xMi0zNy4xNiwxLjA5LTEuMDloOS44NGwxLjA5LDEuMDl2MTAuOTNsLTE3LjQ5LDQzLjcyaDBaIi8+CiAgICAgICAgPHBhdGggY2xhc3M9ImNscy00IiBkPSJtMTM1LjQ1LDEzMS42OGwtMS4wOS0xLjA5di0zMS42N2MwLTUuNDYtMi4xNC05LjctOC43NC05Ljg0LTMuMzktLjA5LTcuMjcsMC0xMS40Mi4xN2wtLjYyLjYzdjQwLjdzLTEuMDksMS4wOS0xLjA5LDEuMDloLTEzLjExbC0xLjA5LTEuMDl2LTUzLjA1bDEuMDktMS4wOSwyOS41MS0uMjdjMTQuNzgsMCwyMC43NywxMC4xNiwyMC43NywyMS42MnYzMi43OWwtMS4wOSwxLjA5aC0xMy4xMloiLz4KICAgICAgPC9nPgogICAgPC9nPgogIDwvZz4KPC9zdmc+
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 3252
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/svg+xml
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: svg
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240423T151155Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sebastian.winter@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sebastian.winter@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1bbf7eb0-658a-4a96-b6ac-444a6988eee2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sebastian.winter@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240423T151155Z
