---
ID: "b3d6330a-19da-47c7-b389-c91ccfafee8f"
Parent: "a2e46b3a-3b3f-4096-ab3b-89a5ef2e00c6"
Template: "a2e46b3a-3b3f-4096-ab3b-89a5ef2e00c6"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Rendering Parameters/Text and Image/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc496601-3e4b-4a22-9a66-2be451102ec9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240220T150145Z
