---
ID: "c88106b4-ce79-4dcc-8ed8-532a08b2f67f"
Parent: "86476269-4b91-4dee-980b-3928d3ece04f"
Template: "86476269-4b91-4dee-980b-3928d3ece04f"
Path: /sitecore/templates/Project/SugconEuSite/App Route/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{899228A0-A4CE-570A-AE24-97566AF3DAB6}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{AA09D219-C19B-4FAF-BF18-EE6544DC5C01}">
        <p
          uid="{BBA6CC61-9E8A-4A7F-830F-4E96A3DD87F8}"
          key="Main"
          md="{DA8ED4DE-A84C-4243-AE5F-F6F36858F5F7}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144847Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb1a2292-25af-4d69-b76d-e4b388f7bd8d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220512T141144Z
