---
ID: "6683bc8d-493d-5c78-aa4c-8cd5a7f5b610"
Parent: "b2bfea77-e196-5b74-9992-315ed471c5eb"
Template: "b2bfea77-e196-5b74-9992-315ed471c5eb"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-SitecoreContext/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144918Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7d2074d4-b9c0-42b5-b96c-c345a42ca508"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144918Z
