---
ID: "a28bc6cf-9007-4d0f-b3fd-83c7eed46d99"
Parent: "9b8718c0-ea1d-4963-8d6a-18b9a75fa1d6"
Template: "9b8718c0-ea1d-4963-8d6a-18b9a75fa1d6"
Path: /sitecore/templates/Feature/Sugcon/Sugcon Base Components/Rendering Parameters/Speaker/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d2b9f11c-1883-4234-b565-65c2674fd497"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220520T142935Z
