---
ID: "9fb5c544-bb8d-5e5e-b0ef-6058a7cf9830"
Parent: "ddad1561-16c3-546c-be8e-f28cdfb650a0"
Template: "ddad1561-16c3-546c-be8e-f28cdfb650a0"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-Multilingual Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144940Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7f495b5-7029-4fd3-a0f7-7f9dc138bb62"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144940Z
