---
ID: "277fd545-7e30-495c-afef-a20159d06232"
Parent: "cffdf442-fd81-498b-842c-72a6ca67e0ea"
Template: "86864760-3b8b-4e79-927e-0addcd14055d"
Path: "/sitecore/content/MvpSite/Home/Application-Closed/Page Components/Application Hero"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "00f0228c-aff3-4ab7-ac98-e4175a53bf32"
      Hint: HeroTitle
      Value: Application
    - ID: "066f7e92-30ad-4198-b138-b40ccaec6d20"
      Hint: HeroLink
      Value: |
        <link text="Sitecore MVPs 2022 Applications are closed" linktype="external" url="/" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211130T202623Z
    - ID: "3489c7a2-efe1-49e0-a3d7-271183c4f255"
      Hint: HeroImage
      Value: |
        <image mediaid="{75E92DFC-F50D-40C7-824F-EEEB8D58B5D6}" />
    - ID: "53ee3e16-ba10-4013-959e-9a652a533845"
      Hint: HeroSubtitle
      Value: Sitecore MVP Program
    - ID: "69db2d7e-db5e-4a02-8580-0bcfb77b5482"
      Hint: HeroDescription
      Value: The MVP Applications are now closed.
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "73871b9b-36c1-437a-b454-4c62bc23d6f2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tamas
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211201T065459Z
