---
ID: "6cad6dd4-2ed6-5ef9-bdfa-c5e142999fee"
Parent: "94cae9b1-0c2f-50b1-bcbe-6bf12d9e8182"
Template: "94cae9b1-0c2f-50b1-bcbe-6bf12d9e8182"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-ItemLink-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144849Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fd0f9a88-cec4-4f18-a204-5a0ee45f5292"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144849Z
