---
ID: "a14b0944-1bec-5f38-b3f2-991b68ee1cda"
Parent: "75c8a98f-64e7-5e91-918a-5e5d75999720"
Template: "75c8a98f-64e7-5e91-918a-5e5d75999720"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-FieldUsage-Date/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144857Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c3aeadb2-e9c9-437a-8e17-d55aa1bcfb78"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144857Z
