---
ID: "ead2da16-2304-4833-9bb2-094fefb46b64"
Parent: "d296373d-623e-461b-8d7a-c274e23cbedb"
Template: "a054184c-3b20-4c2b-ab04-c8a03acd5522"
Path: /sitecore/content/MvpSite/Home/Application/Admin/Applications/Review Settings
BranchID: "ef8dd6f4-1bb8-4831-a1a6-defa3594051a"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{9AC6DDA3-8785-4C63-A2AB-457D8CC56D19}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{E387F358-181C-493E-9C8F-1AA3569C9EA1}"
              p:before="*"
              s:ds="{EA2DD559-66CB-4EDB-BCDE-9F7925C010C3}"
              s:id="{42271165-1389-4C42-BEE9-07FF655DC42C}"
              s:par="CacheClearingBehavior=Clear on publish&amp;CSSStyles"
              s:ph="/main/column-container-{161E50E8-4B34-406D-9C7D-E7BE7DEEFB19}-0" />
            <r
              uid="{161E50E8-4B34-406D-9C7D-E7BE7DEEFB19}"
              p:after="r[@uid='{E387F358-181C-493E-9C8F-1AA3569C9EA1}']"
              s:id="{57805937-D345-4A28-8DDF-C62EE43D8EBA}"
              s:par="CacheClearingBehavior=Clear on publish&amp;CSSStyles"
              s:ph="main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231117T144908Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ed7gR4aY22
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ed7gR4aY22
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "37261807-3df2-462c-bfb3-6f9c4e13bd7c"
    - ID: "b1ece12f-b2c9-44e6-92a3-c5dfd6514b59"
      Hint: MenuTitle
      Value: Review Settings
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ed7gR4aY22
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231117T194956Z
