---
ID: "261fccde-d431-546e-b809-ea57a2ed8340"
Parent: "d5b078de-3a6d-5aae-9c5f-567e4f5bffff"
Template: "d5b078de-3a6d-5aae-9c5f-567e4f5bffff"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-Layout-Reuse/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144914Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c387fd80-5adc-4963-9915-d7a7a0c62b2f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144914Z
