---
ID: "09546f22-cd05-4989-9cfe-64487403380a"
Parent: "efe98bae-b170-4b27-b997-910263a64635"
Template: "a054184c-3b20-4c2b-ab04-c8a03acd5522"
Path: /sitecore/content/MvpSite/Home/Application/Admin/Roles/New
BranchID: "ef8dd6f4-1bb8-4831-a1a6-defa3594051a"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{9AC6DDA3-8785-4C63-A2AB-457D8CC56D19}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221003T130352Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iva@sitecore.net
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a760ecfe-ef16-4900-9aa5-4a70b3a05252"
    - ID: "b1ece12f-b2c9-44e6-92a3-c5dfd6514b59"
      Hint: MenuTitle
      Value: New Role
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "c58ed264-1f55-4aa3-a30e-da12ce43cb38"
      Hint: RequiresAuthentication
      Value: 1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221003T130400Z
    - ID: "efc0a3c7-6993-47d2-ba85-10b44961916e"
      Hint: IncludeInMenu
      Value: 
