---
ID: "569344a8-49a5-585f-a9c6-8fe6bcb270a7"
Parent: "7c2093f5-6fa3-56d8-acc3-d1a549a2aac0"
Template: "7c2093f5-6fa3-56d8-acc3-d1a549a2aac0"
Path: "/sitecore/templates/Project/xmcloudpreview/Styleguide-Explanatory-Component/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220420T144849Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5789eec2-bf73-45c7-be45-805e8abcdf7e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220420T144849Z
