name: CI-CD - MVP Site
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/deploy_azureWebapp.yml
      - 'headapps/MvpSite/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/deploy_azureWebapp.yml
      - 'headapps/MvpSite/**'

jobs:

  build-dotnet:
    uses: ./.github/workflows/build_DotNet.yml
    with:
      buildConfiguration: Release
      solution: headapps/MvpSite/XMC-Introduction-MVP.sln

  deploy-mvp-staging:
    uses: ./.github/workflows/deploy_azureWebapp.yml
    needs: build-dotnet
    with:
      buildConfiguration: Debug
      projectLocation: headapps/MvpSite/MvpSite.Rendering
      assetName: Mvp-Staging
      webAppName: Mvp-Staging
    secrets:
      publishingProfile: ${{ secrets.STAGING_MVP_WEBAPP_PUBLISHING_PROFILE }}
      
  deploy-mvp-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-mvp-staging 
    uses: ./.github/workflows/deploy_azureWebapp.yml
    with:
      buildConfiguration: Release
      projectLocation: headapps/MvpSite/MvpSite.Rendering
      assetName: Mvp-prod
      webAppName: Mvp-Production
    secrets:
      publishingProfile: ${{ secrets.PROD_MVP_WEBAPP_PUBLISHING_PROFILE }}
