name: CI-CD - SUGCON EU
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_EU.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconEuSxa/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_EU.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconEuSxa/**'

jobs:

  build-eu-site:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon/SugconEuSxa

  deploy-eu-site:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-eu-site
    if: always() && 
        (github.repository_owner == 'Sitecore' && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))) &&
        needs.build-eu-site.result != 'failure' &&
        needs.build-eu-site.result != 'cancelled'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_EU_PROJECT_ID }}