name: CI-CD - SUGCON 24 - STORYBOOK
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_24_STORYBOOK.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'headapps/Sugcon2024/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_24_STORYBOOK.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'headapps/Sugcon2024/**'

jobs:

  build-sugcon24-storybook:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs_Storybook.yml
    with:
      workingDirectory: ./headapps/Sugcon2024

  deploy-sugcon24-storybook:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-sugcon24-storybook
    if: always() && 
        needs.build-sugcon24-storybook.result != 'failure' &&
        needs.build-sugcon24-storybook.result != 'cancelled'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_24_STORYBOOK_PROJECT_ID }}