name: CI-CD - MVP Site
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/deploy_azureWebapp.yml
      - 'src/**/rendering/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/deploy_azureWebapp.yml
      - 'src/**/rendering/**'

jobs:

  build-dotnet:
    uses: ./.github/workflows/build_DotNet.yml
    with:
      buildConfiguration: Release

  deploy-mvp-staging:
    uses: ./.github/workflows/deploy_azureWebapp.yml
    needs: build-dotnet
    if: github.repository_owner == 'Sitecore' && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) 
    with:
      buildConfiguration: Debug
      projectLocation: src/Project/MvpSite/rendering
      assetName: Mvp-Staging
      webAppName: Mvp-Staging
    secrets:
      publishingProfile: ${{ secrets.STAGING_MVP_WEBAPP_PUBLISHING_PROFILE }}
      
  deploy-mvp-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-mvp-staging 
    uses: ./.github/workflows/deploy_azureWebapp.yml
    with:
      buildConfiguration: Release
      projectLocation: src/Project/MvpSite/rendering
      assetName: Mvp-prod
      webAppName: Mvp-Production
    secrets:
      publishingProfile: ${{ secrets.PROD_MVP_WEBAPP_PUBLISHING_PROFILE }}
